version: '3.7'

x-app_environment: &app_environment
  environment:
    - DEBUG=True
    - POSTGRES_PASSWORD=postgres

services:
  akt_backend:
    tty: true
    image: alpine
    restart: on-failure
    entrypoint: sh -x ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    build:
      context: ./back
    depends_on:
      - db
    ports:
    - 8000:8000
    <<: *app_environment
  akt_frontend:
    image: node
    restart: unless-stopped
    volumes:
      - ./akt_front/
    command: npm start
    build:
      context: ./front
    depends_on:
      - akt_backend
    ports:
      - 3000:3000
  db:
    image: postgres:12.3-alpine
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - 15202:5432
    <<: *app_environment

volumes:
  postgresdata: