# Generated by Django 4.1.2 on 2022-10-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=15, verbose_name='Код')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена')),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Цена специального предложения')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('measurement', models.CharField(max_length=5, verbose_name='Ед. измерения')),
                ('united_purchases', models.BooleanField(default=False, verbose_name='Совместные покупки')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('show_main', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Название свойства')),
                ('value', models.CharField(max_length=100, verbose_name='Значение свойства')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Опиция',
                'verbose_name_plural': 'Опции',
            },
        ),
    ]
